name: My First Workflow    #Diplay the name of the workflow unders actions tab 

on: push

jobs:
    first_job: 
        runs-on: ubuntu-latest
        steps:
            - name: Git Checkout
              uses: actions/checkout@v7 
              
            - name: Welcome Message
              run: echo "My First Github Actions Job"

            - name: List Files
              run:  ls

            - name: Read File
              run: cat README.md

    second-job:
        runs-on: ubuntu-latest

        steps:
          - name: Git Checkout
            uses: actions/checkout@v7

          - name: Welcome Message
            run: echo "Welcome To the Work of My Repo"

          - name: List Files
            run: ls -la

          - name: Read Files
            run: cat README.md          

