name: Second Sample pipeline
on:
    push: 
jobs:
    second-job:
        runs-on: ubuntu-latest
        steps:
            - name: Git Checkout
              uses: actions\checkout@v7
            - name: Perform Installation
              run: sudo apt-get updaye -y && sudo apt-get install cowsay -y 
            - name: Perform steps
              run: |
                 cowsay -f dragon "Move or I will burn" >> dragon.txt
                 cat dragon.txt  
    
